repos:
  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.11.0'
    hooks:
      - id: talisman-commit
  - repo: local
    hooks:
      - id: local-pre-commit
        name: unit-test
        entry: bash -c "$(git rev-parse --show-toplevel)/scripts/pre-commit.sh"
        language: system
        pass_filenames: false
        types: [ text ]
        verbose: true