#!/bin/bash

__frontend_standalone() {
  yarn --cwd=./frontend install && yarn --cwd=./frontend start
}

__frontend_test() {
  yarn --cwd=./frontend install && yarn --cwd=./frontend test
}

__backend_standalone() {
  ./gradlew clean bootRun
}

__backend_test() {
  ./gradlew cleanTest test
}

__local_install_git_hooks() {
  if ! type pre-commit >/dev/null; then
    brew install pre-commit
  fi

  pre-commit install -f

  echo "Installed git hooks"
}

__service() {
  yarn --cwd=./frontend install && yarn --cwd=./frontend build

  cp -R ./frontend/build/* ./src/main/resources/static

  __backend_standalone
}

CMD=${1:-}
__"$CMD"
